# Generated by Django 4.1.2 on 2023-07-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("certificate_gen", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certificate_model",
            name="id",
        ),
        migrations.AddField(
            model_name="certificate_model",
            name="certificate_number",
            field=models.CharField(
                default="DEFAULT_VALUE",
                editable=False,
                max_length=6,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
